#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

privacy_policy_in:
  path: /privacyIn
  controller: "src/Controller/RoutingController::privacyIn"
privacy_policy_out:
  path: /privacyOut
  controller: "src/Controller/RoutingController::privacyOut"
terms_of_use_in:
  path: /useIn
  controller: "src/Controller/RoutingController::useIn"
terms_of_use_out:
  path: /useOut
  controller: "src/Controller/RoutingController::useOut"
home_in:
  path: /test
  controller: "src/Controller/FirstController::test"
services:
  path: /services
  controller: "src/Controller/RoutingController::services"
edit_personal:
  path: /editPersonal
  controller: "src/Controller/FirstController::editPersonal"
home_out:
  path: /homeOut
  controller: "src/Controller/RoutingController::acceuil"
residentList:
  path: /resident/show
  controller: "src/Controller/ResidentController::getResident"
aboutUsIn:
  path: /homeUsIn
  controller: "src/Controller/RoutingController::aboutUsIn"
lobby:
  path: /lobby
  controller: "src/Controller/RoutingController::lobby"
room_go:
  path: /device/{roomId}
  controller: "src/Controller/DeviceController::device"
device_info:
  path: /consult/{roomId}
  controller: "src/Controller/HistoController::histo.consult"
rooms:
  path: /rooms
  controller: "src/Controller/RoomSelectionController::room_selection"
temperature:
  path: /temperature
  controller: "src/Controller/DeviceController::devicetemp"
lighting:
  path: /lighting
  controller: "src/Controller/DeviceController::devicelight"
security:
  path: /security
  controller: "src/Controller/DeviceController::devicesecure"
camera:
  path: /camera
  controller: "src/Controller/DeviceController::devicecamera"
